### ISSUE TITLE
Add function for vertical strain rates and verify with existing scripts

### ISSUE THREAD

**Issue by glugeorge** [ldeo-glaciology/XApRES#11]
Adapt ImpDAR's phase2range function and assign to a class in ApRESDefs. Moving over issue from: https://github.com/ldeo-glaciology/XApRES/issues/5

**Comment by jkingslake** [comment]
did #14 address this @glugeorge ? Or only partially, in any case, maybe updating this issue with a note about #14 could be useful here.

**Comment by glugeorge** [comment]
#14 addresses this partially. Still need to add and test additions to the base calculations, namely the option to include wrapping.

**Comment by glugeorge** [comment]
Revisiting this, the next step is to create a notebook that uses some of our winter data (where nothing unusual is happening) to validate our script

**Comment by jkingslake** [comment]
cc @hoffmaao

**Comment by jkingslake** [comment]
#57 adds the capability to compute strain rates. 
E.g.
```
import xapres as xa
LTG = xa.load.load_zarr('/Users/jkingslake/Documents/science/ApRES/TG_apres/notebooks/zarrs/LTG_stacked.zarr').load()
dLTG = LTG.profile_stacked.displacement_timeseries().compute()
dLTG.strain_rate.plot()
```
produces
![image](https://github.com/user-attachments/assets/0dd457f7-e39a-40be-b1e5-c61939f4fa09)

I will close this now and start another issue exclusively about comparing results across different codes
