### ISSUE TITLE
Xarrays stored on bucket have profiles not formatted for complex64 

### ISSUE THREAD

**Issue by glugeorge** [ldeo-glaciology/XApRES#12]
I've been trying to unpack why our python scripts are so different from the MATLAB ones. Still working on converting the MATLAB vertical velocity calculations to python. But before I dive too deep into this, I realized that when I try loading in the existing xarrays stored as zarrs with this code:
`def reload(site):
    filename = f'gs://ldeo-glaciology/apres/greenland/2022/single_zarrs/{site}'
    ds = xr.open_dataset(filename,
        engine='zarr', 
        chunks={}) 
    return ds

ds_101 = reload("A101")`
ds_101 looks like this:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/25989736/215360112-e4e3df9a-6bfd-4ab5-a09e-5fa1b7530e52.png">
And indeed the profile variable has lost its complex component.

On the otherhand, if I use the load_all function to access the .DAT files directly from the cloud with this command:
`xa = ApRESDefs.xapres(max_range=1400)
xa.load_all(directory='gs://ldeo-glaciology/GL_apres_2022/A101', 
            remote_load = True,
            file_numbers_to_process=range(0,2)
           )
xa.data`
The complex nature of the profile is preserved. 
<img width="736" alt="image" src="https://user-images.githubusercontent.com/25989736/215360177-eea15d6a-3375-44be-9ecc-7447637ca530.png">

So it seems like there's some bug that only keeps the real portion of the profile during the process of converting them into zarrs.

**Comment by glugeorge** [comment]
It could also be an issue with loading it in, I'm not too familiar with how to access zarrs

**Comment by jkingslake** [comment]
So they come out as reals when you load in the zarrs? Or are they complex
numbers with a different precision than 64 bit?

**Comment by glugeorge** [comment]
They come out as reals. Even though the description says complex-type, the actual values are just real floats.
<img width="737" alt="image" src="https://user-images.githubusercontent.com/25989736/215361309-211b4882-eda0-4a59-a81d-c5aaae4400d9.png">

**Comment by glugeorge** [comment]
I found the bug. In the 3rd cell of write_big_zarrs.ipynb:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/25989736/215362360-15225851-edf9-4989-ae11-71b16eabf9df.png">
In write_big_zarrs, it assigns everything float64. I think we may need to re-run this process to get xarrays with the proper complex128 for the profile and profile_stacked variables

Quick fix for this would be to add:
encoding['profile']= {"dtype": "complex128"}
encoding['profile_stacked']= {"dtype": "complex128"}
after the buggy line above

**Comment by glugeorge** [comment]
Removed encoding line in write_big_zarrs.ipynb. New zarrs can be accessed with:
def reload(site):
    filename = f'gs://ldeo-glaciology/apres/greenland/2022/single_zarrs_noencode/{site}'
    ds = xr.open_dataset(filename,
        engine='zarr', 
        chunks={}) 
    return ds

ds_101 = reload("A101")
ds_103 = reload("A103")
ds_104 = reload("A104")
