### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/XApRES#21]
regularly scheduled tests are suddenly failing at the stage shere it tries to update the virtual environment used in the github action: https://github.com/ldeo-glaciology/xapres_package/actions/runs/4721650983/jobs/8375178519#step:4:3296

`Installing pip dependencies: ...working... ::warning::Pip subprocess error:%0AERROR: Could not find a version that satisfies the requirement codecov (from versions: none)%0AERROR: No matching distribution found for codecov%0A%0A`

any thoughts @jbusecke?

**Comment by jkingslake** [comment]
some hints here: https://github.com/Chisanan232/PyMock-API/pull/46/files#diff-f53a023eedfa3fbf2925ec7dc76eecdc954ea94b7e47065393dbad519613dc89

**Comment by jbusecke** [comment]
Seems like the old uploader is deprecated. They have a [migration guide](https://docs.codecov.com/docs/deprecated-uploader-migration-guide#python-uploader)

**Comment by jkingslake** [comment]
Thanks! Turns out I just needed to merge #1, which was about updating the version of codecov to v3.
