### ISSUE TITLE
renaming and slight refactor

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/XApRES#24]
Before we go too much further with this package, I think we should do a little refactoring and rename some important things. 

- I think we should rename the whole package XApRES (or ApyRES). The current name (xapres_package), was just something i chose to experiment with making a package. We should change it. 
- We should move `load_single`, `load_dat_file`, and `list_files` out of `xapres`, but still in `ApRESDefs`.
- Remove `load_all` and put its functionality into `xapres.__init__`. So creating a new xapres is the same as running load_all is currently.
- We should change the name of ApRESDefs to `load` or something similar. Most of the functionality in there is about loading data (and see next point for other functionality).
- We should move the `coherence` and `generate_range_diff` functions to a separate library, maybe called 'proc' for processing, or something similar. 
- at the end of `xapres.__init__` add in the `.sonify` and `.dB` methods to the opened xapres. I think this will involve moving the definitions of sonify and dB out of `load_zarr`

@glugeorge @Elizabethcase , what do you think?

**Comment by Elizabethcase** [comment]
Agree re: renaming package. The sooner the better. 

Different libraries could be: load, plot, preprocess (remove noisy chirps, chop clipped signal, check for clippping, etc), processing (could be broken up into time analysis, polarmetric, repeat, and cmp libraries)

**Comment by jkingslake** [comment]
many of these changes are in PR #35. I did not remove `load_all`, but I did add a wrapper around the who class, which is attempted to solve the same problem that removing `load_all` was; i.e. making it simpler to make xarrays from dat files without necessarily having to  do the whole OO thing of initializing an object then running its methods. 

#35 does not change the name of the package, but we should do that next.

**Comment by jkingslake** [comment]
#35 does now change the name of the package to xapres. 

and #35 has been merged, so I will close this issue
