### ISSUE TITLE
todo: use datatree to group data

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/XApRES#9]
cc @glugeorge 

The idea it to use [datatrees](https://github.com/xarray-contrib/datatree) to group together data from ApRES instruments in the same survey. 

@TomNicholas, this is the project we talked about that could be a good use case for datatrees. There are three zarrs stored in a google bucket, each containing similar data from different ice-penetrating radar units which ran for three months in 2022 (and are, hopefully, still running now!). 

The zarrs have the same dimension names, but the coordinates have different values, particularly the `time`, `AFGain`, `attenuator` and `filename` coordinates. 

Let us know if you think this is a good use case.

This code loads the data:

```
import xarray as np
def reload(site):
    filename = f'gs://ldeo-glaciology/apres/greenland/2022/single_zarrs/{site}'
    ds = xr.open_dataset(filename,
        engine='zarr', 
        chunks={}) 
    return ds
A101 = reload("A101')
A103 = reload("A103')
A104 = reload("A104')
```

**Comment by TomNicholas** [comment]
Sounds reasonable to me! Let me know if you have specific questions about datatree :slightly_smiling_face:

**Comment by jkingslake** [comment]
Still hoping to get round to this. 

We also have multiple datasets from the same site that are potentially unaligned because the data was collected using different settings. 

cc @glugeorge

**Comment by jkingslake** [comment]
I started using datatree when looking at data from three sites on Thwaites Glacier ([here](https://github.com/ldeo-glaciology/TG_apres/blob/main/notebooks/initial_plotting_of_TG_data.ipynb)). It was quite straightforward to do. 

```
import xarray as xr
from datatree import DataTree
LTG = xr.open_dataset('gs://ldeo-glaciology/apres/thwaites/continuous/ApRES_LTG/zarr/full.zarr',
                      engine = 'zarr',
                      chunks = {})
LK1 = xr.open_dataset('gs://ldeo-glaciology/apres/thwaites/continuous/ApRES_Lake1/zarr/full.zarr',
                      engine = 'zarr',
                      chunks = {})
LK2 = xr.open_dataset('gs://ldeo-glaciology/apres/thwaites/continuous/ApRES_Lake2/zarr/full.zarr',
                      engine = 'zarr',
                      chunks = {})
ds_list = [LTG, LK1, LK2]
dt = DataTree.from_dict({"LTG": ds_list[0], "LK1": ds_list[1], "LK2": ds_list[2]})
```
It allows you to do some simple things very easily, e.g.,
```
dt = dt.drop_vars(['chirp', 'profile'])
```
but i havent used the data tree extensively yet.

**Comment by TomNicholas** [comment]
FYI @jkingslake I'm hoping to release `xarray.DataTree` and archive `datatree.DataTree` literally today! There are differences in behaviour so I would suggest you just use `xarray.DataTree` (it's available in xarray `main` right now) off the bat.
